modid="sandscript" # required `[a-z0-9-_]{4,15}`
version="1.0.0" # required Semver Enforced!
title="SandScript" # optional DEFAULT: modid
description="Write addons in JSR223 languages."  # optional DEFAULT: ""
entrypoint="space.bbkr.sandscript.SandScript" # required
authors = [ # required 1
    "B0undarybreaker"
]
url = "https://github.com/boundarybreaker/sandscript" # optional DEFAULT: ""
side = "COMMON" # optional [SERVER, CLIENT, COMMON] DEFAULT: "COMMON"